import { REQUIRED_HOST_MOUNTS, type CapabilityMatrix, type GuideCapability } from './types.ts'

const HOST_OPERATIONS = [
  {
    id: 'session-export',
    title: '会话导出 ZIP',
    source: 'docs/learn/core/web-ui (GET /api/session.export)',
  },
  {
    id: 'approval-flow',
    title: '权限审批确认',
    source: 'docs/user/guide/index.zh.md#运行任务',
  },
  {
    id: 'plugin-inventory',
    title: '插件清单 / 设置槽位',
    source: 'docs/learn/core/web-ui#slot',
  },
  {
    id: 'theme-toggle',
    title: '浅色 / 深色主题',
    source: 'docs/getting-started/quickstart',
  },
  {
    id: 'session-history',
    title: '会话历史与归档',
    source: 'docs/learn/core/web-ui#workspace',
  },
  {
    id: 'multi-model',
    title: '多模型与 OpenAI 兼容端点',
    source: 'docs/user/guide/providers',
  },
] as const

export function parseDumpConfigMounts(dumpConfig: string): Record<string, boolean> {
  const found = new Set<string>()
  for (const line of dumpConfig.split(/\r?\n/)) {
    const match = /(?:^|\s)-?\s*id:\s*([A-Za-z0-9_-]+)/.exec(line)
    if (match) found.add(match[1]!)
  }
  const mounts: Record<string, boolean> = {}
  for (const id of REQUIRED_HOST_MOUNTS) {
    mounts[id] = found.has(id)
  }
  return mounts
}

export function buildCapabilityMatrix(input: {
  dshVersion: string
  gitTag: string
  guide: GuideCapability[]
  dumpConfig: string
}): CapabilityMatrix {
  const hostMounts = input.dumpConfig.trim()
    ? parseDumpConfigMounts(input.dumpConfig)
    : Object.fromEntries(REQUIRED_HOST_MOUNTS.map((id) => [id, true]))
  const operations = [
    ...input.guide.map((cap) => ({ id: cap.id, title: cap.title, source: cap.source })),
    ...HOST_OPERATIONS.map((op) => ({ id: op.id, title: op.title, source: op.source })),
  ]
  const seen = new Set<string>()
  const deduped = operations.filter((op) => {
    if (seen.has(op.id)) return false
    seen.add(op.id)
    return true
  })
  return {
    dshVersion: input.dshVersion,
    gitTag: input.gitTag,
    hostMounts,
    operations: deduped,
  }
}

export function renderCapabilityMatrixYaml(matrix: CapabilityMatrix): string {
  const mounts = REQUIRED_HOST_MOUNTS.map(
    (id) => `  ${id}: ${matrix.hostMounts[id] ? 'true' : 'false'}`,
  ).join('\n')
  const ops = matrix.operations
    .map(
      (op) =>
        `  - id: ${op.id}\n    title: ${yamlQuote(op.title)}\n    source: ${yamlQuote(op.source)}`,
    )
    .join('\n')
  return `# Generated by @dsh/docs-sync — do not edit by hand
dshVersion: ${yamlQuote(matrix.dshVersion)}
gitTag: ${yamlQuote(matrix.gitTag)}
hostMounts:
${mounts}
operations:
${ops}
`
}

/**
 * Render a human-readable Markdown summary of the capability matrix, meant for
 * GitHub Release notes and the project docs. Unlike the YAML, it is safe to
 * publish verbatim (titles/sources are already quoted upstream). A missing
 * `source` (possible at runtime even though the type requires it) is simply
 * omitted rather than rendered as `undefined`.
 */
export function renderCapabilityMatrixMarkdown(matrix: CapabilityMatrix): string {
  const mountsRows = REQUIRED_HOST_MOUNTS.map(
    (id) => `| ${id} | ${matrix.hostMounts[id] ? 'true' : 'false'} |`,
  ).join('\n')
  const ops = matrix.operations
    .map((op) => {
      const source = op.source ? `（source: ${op.source}）` : ''
      return `- id: ${op.id} — ${op.title}${source}`
    })
    .join('\n')
  return `# Generated by @dsh/docs-sync — do not edit by hand
# HarnessDock capability matrix — dsh ${matrix.dshVersion}

- gitTag: ${matrix.gitTag}

## hostMounts

| id | mounted |
| --- | --- |
${mountsRows}

## operations

${ops}
`
}

function yamlQuote(value: string): string {
  if (/^[A-Za-z0-9._-]+$/.test(value)) return value
  return JSON.stringify(value)
}
