import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { HOST_PROFILES, TAURI_ANDROID_HOST_PROFILE, TAURI_HOST_PROFILE, TAURI_IOS_HOST_PROFILE } from '../../packages/bootstrap/src/index.ts'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const readJson = (relative: string): Record<string, any> => JSON.parse(readFileSync(path.join(repoRoot, relative), 'utf8'))
const unsupportedNativeV02 = ['notifications', 'pushNotifications', 'deepLinks', 'secureCredentials', 'backgroundExecution'] as const

describe('Tauri v0.2 host contract', () => {
  it('promotes Tauri desktop and mobile as stable product hosts', () => {
    expect(TAURI_HOST_PROFILE.channel).toBe('stable')
    expect(TAURI_HOST_PROFILE.capabilities.runtimes).toEqual(['local', 'remote'])
    expect(TAURI_HOST_PROFILE.capabilities.autoUpdate).toBe(true)
    expect(TAURI_HOST_PROFILE.capabilities.tray).toBe(true)
    expect(TAURI_HOST_PROFILE.capabilities.notifications).toBe(false)
    expect(TAURI_IOS_HOST_PROFILE.capabilities.runtimes).toEqual(['remote'])
    expect(TAURI_ANDROID_HOST_PROFILE.capabilities.runtimes).toEqual(['remote'])
    expect(Object.keys(HOST_PROFILES)).toEqual(expect.arrayContaining(['tauri', 'tauri-ios', 'tauri-android']))
    expect(Object.keys(HOST_PROFILES).some((key) => key.startsWith('perry'))).toBe(false)
  })

  it('does not advertise native services that v0.2 has not implemented', () => {
    for (const capability of unsupportedNativeV02) {
      expect(TAURI_HOST_PROFILE.capabilities[capability]).toBe(false)
      expect(TAURI_IOS_HOST_PROFILE.capabilities[capability]).toBe(false)
      expect(TAURI_ANDROID_HOST_PROFILE.capabilities[capability]).toBe(false)
    }
  })

  it('keeps repository, Tauri application and Rust crate versions aligned', () => {
    const root = readJson('package.json')
    const tauri = readJson('apps/tauri/src-tauri/tauri.conf.json')
    const releaseManifest = readJson('release-manifest.json')
    const shellManifest = readJson('packages/plugin-harness-shell/manifest.json')
    const cargo = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/Cargo.toml'), 'utf8')
    expect(tauri.version).toBe(root.version)
    expect(releaseManifest.version).toBe(root.version)
    expect(releaseManifest.shell.version).toBe(root.version)
    expect(shellManifest.version).toBe(root.version)
    expect(cargo).toContain(`version = "${root.version}"`)
    expect(tauri.identifier).toBe('com.harnessdock.client')
  })

  it('publishes Full-only Tauri assets while retaining thin as legacy source only', () => {
    const candidate = readFileSync(path.join(repoRoot, '.github/workflows/tauri-candidate.yml'), 'utf8')
    const release = readFileSync(path.join(repoRoot, '.github/workflows/release.yml'), 'utf8')
    expect(candidate).toContain('Verify full runtime before packaging')
    expect(release).not.toContain('-thin')
    expect(release).toContain('expected 20 non-empty assets')
    expect(release).toContain('latest.json')
    expect(release).toContain('.app.tar.gz.sig')
    expect(release).toContain('release asset must match exactly once')
    expect(release).toContain('missing runtime root manifest')
    expect(candidate).toContain('Require signed Tauri updater material')
    expect(candidate).not.toContain('@dsh/desktop')
  })

  it('brands install, uninstall and mobile icon generation from one HarnessDock source', () => {
    const tauri = readJson('apps/tauri/src-tauri/tauri.conf.json')
    const windows = tauri.bundle.windows
    expect(windows.allowDowngrades).toBe(false)
    expect(windows.webviewInstallMode).toEqual({ type: 'embedBootstrapper', silent: true })
    expect(windows.nsis.installerIcon).toBe('icons/icon.ico')
    expect(windows.nsis.uninstallerIcon).toBe('icons/icon.ico')
    expect(windows.nsis.installMode).toBe('currentUser')
    expect(windows.nsis.languages).toEqual(['English', 'SimpChinese', 'TradChinese'])

    const source = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/icons/app-icon.png'))
    expect(source.subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a')
    expect(source.readUInt32BE(16)).toBe(1024)
    expect(source.readUInt32BE(20)).toBe(1024)

    const candidate = readFileSync(path.join(repoRoot, '.github/workflows/tauri-candidate.yml'), 'utf8')
    expect(candidate).toContain('cargo tauri icon src-tauri/icons/app-icon.png')
    expect(candidate).toContain('Verify Windows installer uses HarnessDock icon')
    expect(candidate).toContain('Replace default Android launcher icons with HarnessDock')
    expect(candidate).toContain('Replace default iOS app icons with HarnessDock')
  })

  it('publishes only after exact successful main candidate and same-SHA CI', () => {
    const workflow = readFileSync(path.join(repoRoot, '.github/workflows/release.yml'), 'utf8')
    expect(workflow).toContain('workflow_run:')
    expect(workflow).toContain('- tauri-candidate')
    expect(workflow).toContain('candidate is stale:')
    expect(workflow).toContain('candidate is not green:')
    expect(workflow).toContain('no successful same-SHA main CI found')
    expect(workflow).toContain('gh release upload "$RELEASE_TAG" release-assets/* --clobber')
    expect(workflow).toContain('test "$tag_sha" = "$RELEASE_SHA"')
    expect(workflow).not.toContain('--method DELETE')
  })

  it('builds Android candidates in release mode and gates native package size', () => {
    const candidate = readFileSync(path.join(repoRoot, '.github/workflows/tauri-candidate.yml'), 'utf8')
    const smoke = readFileSync(path.join(repoRoot, '.github/workflows/tauri-ci.yml'), 'utf8')
    const release = readFileSync(path.join(repoRoot, '.github/workflows/release.yml'), 'utf8')
    const sizeGate = readFileSync(path.join(repoRoot, 'scripts/check-android-package.mjs'), 'utf8')
    expect(candidate).toContain('cargo tauri android build --apk --aab')
    expect(candidate).not.toContain('cargo tauri android build --release')
    expect(candidate).toContain('node scripts/check-android-package.mjs')
    expect(smoke).toContain('cargo tauri android build --apk')
    expect(smoke).not.toContain('cargo tauri android build --release')
    expect(release).toContain('android-arm64-release.apk')
    expect(release).not.toContain('android-arm64-debug.apk')
    expect(sizeGate).toContain('.so')
  })

  it('keeps local control permissions isolated from remote documents', () => {
    const capability = readJson('apps/tauri/src-tauri/capabilities/local-main.json')
    const remoteHarness = readJson('apps/tauri/src-tauri/capabilities/harness-shell.json')
    expect(capability.remote).toBeUndefined()
    expect(capability.windows).toEqual(['main'])
    expect(capability.permissions).not.toContain('harness-shell')
    expect(remoteHarness.local).toBe(false)
    expect(remoteHarness.windows).toEqual(['harness'])
    expect(remoteHarness.permissions).not.toContain('core:default')
  })

  it('boots directly into the isolated Harness WebView on desktop', () => {
    const tauri = readJson('apps/tauri/src-tauri/tauri.conf.json')
    const android = readJson('apps/tauri/src-tauri/tauri.android.conf.json')
    const ios = readJson('apps/tauri/src-tauri/tauri.ios.conf.json')
    expect(tauri.app.windows[0].visible).toBe(false)
    expect(android.app.windows[0].visible).toBe(true)
    expect(ios.app.windows[0].visible).toBe(true)

    const launcher = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/main.rs'), 'utf8')
    const harnessWindow = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/harness_window.rs'), 'utf8')
    const host = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/lib.rs'), 'utf8')
    const runtime = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/runtime.rs'), 'utf8')
    const web = readFileSync(path.join(repoRoot, 'apps/tauri/web/app.js'), 'utf8')
    expect(launcher).toContain('windows_subsystem = "windows"')
    expect(harnessWindow).toContain('let _ = control.hide()')
    expect(harnessWindow).toContain('control_show')
    expect(harnessWindow).toContain('.decorations(false)')
    expect(host).toContain('tray::create_tray')
    expect(host).toContain('RunEvent::WindowEvent')
    expect(host).toContain('quitting')
    expect(host).toContain('runtime_starting')
    expect(host).toContain('web_action')
    expect(host).toContain('harness_loading')
    expect(host).toContain('harness_safe_mode_restart')
    expect(host).toContain('spawn_blocking')
    expect(host).toContain('starting_processes_empty')
    expect(host).not.toContain('prewarm_settings_window')
    expect(runtime).toContain('gateway_host::stop_managed(&state.gateway)')
    expect(runtime).toContain('runtime_restarting')
    expect(runtime).toContain('Gateway 正在启动，请稍候再停止 Runtime。')
    const runtimeStartClaim = runtime.indexOf('let _starting = RuntimeStartGuard')
    const runtimeStartAdmission = runtime.indexOf('if !allow_restarting', runtimeStartClaim)
    const runtimeStateInspection = runtime.indexOf('let mut removed_dead_runtime', runtimeStartClaim)
    expect(runtimeStartClaim).toBeGreaterThanOrEqual(0)
    expect(runtimeStartAdmission).toBeGreaterThan(runtimeStartClaim)
    expect(runtimeStartAdmission).toBeLessThan(runtimeStateInspection)
    expect(web).toContain('autoStartDesktopRuntime')
    expect(web).toContain("call('runtime_start')")
    expect(web).toContain("call('harness_open'")
    expect(harnessWindow).toContain('startup_recovery_error')
    expect(harnessWindow).toContain('正在恢复 Harness Web')
  })

  it('keeps the independent Harness Shell on demand while Harness Web is mandatory', () => {
    const capability = readJson('apps/tauri/src-tauri/capabilities/harness-shell.json')
    const permission = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/permissions/harnessdock.toml'), 'utf8')
    const shell = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/harness_shell.rs'), 'utf8')
    const shellAsset = readFileSync(path.join(repoRoot, 'packages/plugin-harness-shell/src/web/shell.js'), 'utf8')
    const harnessWindow = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/harness_window.rs'), 'utf8')
    const host = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/lib.rs'), 'utf8')
    const web = readFileSync(path.join(repoRoot, 'apps/tauri/web/app.js'), 'utf8')
    const index = readFileSync(path.join(repoRoot, 'apps/tauri/web/index.html'), 'utf8')
    const settingsCapability = readJson('apps/tauri/src-tauri/capabilities/shell-settings.json')
    const settingsHtml = readFileSync(path.join(repoRoot, 'apps/tauri/web/settings.html'), 'utf8')
    const settingsJs = readFileSync(path.join(repoRoot, 'apps/tauri/web/settings.js'), 'utf8')
    const update = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/update.rs'), 'utf8')
    const cargo = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/Cargo.toml'), 'utf8')
    const tray = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/tray.rs'), 'utf8')
    expect(capability.windows).toEqual(['harness'])
    expect(capability.local).toBe(false)
    expect(capability.platforms).toEqual(['linux', 'macOS', 'windows'])
    expect(capability.remote.urls).toEqual([
      'http://127.0.0.1:*/*',
      'http://127.0.0.1:*',
      'http://localhost:*/*',
      'http://localhost:*',
      'https://127.0.0.1:*/*',
      'https://127.0.0.1:*',
      'https://localhost:*/*',
      'https://localhost:*',
    ])
    expect(capability.remote.urls.every((url: string) => !url.includes('[::1]'))).toBe(true)
    expect(capability.permissions).toEqual([
      'core:event:allow-listen',
      'core:event:allow-unlisten',
      'core:window:allow-start-dragging',
      'harness-shell',
    ])
    expect(readJson('apps/tauri/src-tauri/capabilities/local-main.json').permissions).not.toContain('harness-shell')
    expect(permission).toContain('commands.allow = ["shell_settings_show", "harness_minimize", "harness_toggle_maximize", "harness_window_state", "harness_shell_close", "harness_reload_web", "harness_restart_web", "harness_safe_mode_restart", "harness_clear_quarantine_restart", "update_check", "update_install", "app_quit"]')
    expect(shell).toContain('SHELL_WEB_SCRIPT')
    expect(shell).toContain("'window.close': 'harness_shell_close'")
    expect(shell).toContain('pub async fn harness_shell_close')
    expect(shell).toContain("'runtime.safe-mode': 'harness_safe_mode_restart'")
    expect(shellAsset).toContain('id = \'dsh-harness-shell\'')
    expect(shellAsset).toContain("['web.reload', '刷新 Harness Web']")
    expect(shellAsset).toContain("['runtime.safe-mode', '隔离插件启动']")
    expect(shellAsset).toContain("['app.update.install', '安装 GitHub 更新']")
    expect(shellAsset).toContain('window.__DSH_SHELL_BRIDGE__')
    expect(shellAsset).toContain('dsh-shell-layout')
    expect(shellAsset).toContain('data-menu-toggle')
    expect(shellAsset).toContain('compatibleBridge && bridge.subscribe')
    expect(host).toContain('"shell-safe-mode", "隔离插件启动"')
    expect(host).toContain('"shell-update", "自动更新"')
    expect(host).toContain('stop_managed_processes')
    expect(host).toContain('report_shell_error')
    expect(tray).toContain('"tray-safe-mode", "隔离插件启动"')
    expect(tray).toContain('"tray-update", "自动更新"')
    expect(tray).toContain('window.is_visible().unwrap_or(false) || !loading')
    expect(tray).toContain('crate::update::update_install')
    expect(web).toContain("await openHarnessWithRetry(currentRuntime.appUrl)")
    expect(web).not.toContain('autoOpenHarness')
    expect(web).not.toContain('auto-open-harness')
    expect(index).not.toContain('id="shell-settings"')
    expect(index).toContain('正常启动将直接打开 Harness Web')
    expect(index).toContain('id="desktop-card" class="card hidden"')
    expect(settingsCapability.windows).toEqual(['settings'])
    expect(settingsCapability.permissions).toContain('shell-settings')
    expect(permission).toContain('identifier = "runtime-maintenance"')
    expect(permission).toContain('identifier = "shell-settings"')
    expect(permission).toContain('commands.allow = ["shell_settings_close", "runtime_status", "app_quit"]')
    expect(settingsHtml).toContain('插件诊断')
    expect(settingsHtml).toContain('刷新诊断数据')
    expect(settingsHtml).toContain('统一从主界面的“菜单”执行')
    expect(settingsHtml).toContain('查看 Runtime、插件隔离、更新配置状态')
    expect(settingsHtml).not.toContain('自动更新并重启')
    expect(settingsHtml).toContain('class="settings-page"')
    expect(harnessWindow).toContain('pub async fn shell_settings_show')
    expect(harnessWindow).not.toContain('pub fn control_hide')
    expect(readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/build.rs'), 'utf8')).not.toContain('"control_hide"')
    expect(harnessWindow).toContain('async fn show_settings_window')
    expect(harnessWindow).toContain('.visible(false)')
    expect(harnessWindow).toContain('.center()')
    expect(harnessWindow).toContain('PageLoadEvent::Finished')
    expect(harnessWindow).toContain('show_splash')
    expect(harnessWindow).toContain('restart_harness_web_impl')
    expect(harnessWindow).toContain('clear_quarantine: bool')
    expect(harnessWindow).not.toContain('eval("window.location.reload()")')
    const reloadStart = harnessWindow.indexOf('pub async fn harness_reload_web')
    const restartStart = harnessWindow.indexOf('pub async fn harness_restart_web')
    const reloadEnd = harnessWindow.indexOf('/// Replace the local Runtime/Gateway', reloadStart)
    expect(reloadStart).toBeGreaterThanOrEqual(0)
    expect(restartStart).toBeGreaterThan(reloadStart)
    expect(reloadEnd).toBeGreaterThan(reloadStart)
    expect(harnessWindow.slice(reloadStart, reloadEnd)).toContain('window.reload()')
    expect(harnessWindow.slice(reloadStart, reloadEnd)).toContain('harness_loading')
    expect(harnessWindow.slice(reloadStart, reloadEnd)).not.toContain('window.hide()')
    expect(settingsJs).toContain('const invoke = window.__TAURI__?.core?.invoke')
    expect(settingsJs).toContain("call('shell_settings_close')")
    expect(settingsJs).toContain("lines.join('\\n')")
    expect(settingsJs).toContain('从主界面的“菜单”')
    expect(settingsJs).not.toContain("call('harness_restart_web')")
    expect(settingsJs).not.toContain("call('update_install')")
    expect(settingsHtml).toContain('版本更新')
    expect(settingsHtml).toContain('id="settings-quit"')
    expect(web).toContain('openHarnessWithRetry')
    expect(web).toContain('Native startup owns the normal desktop path')
    expect(readJson('apps/tauri/src-tauri/capabilities/local-main.json').permissions).toContain('splash-status')
    expect(readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/build.rs'), 'utf8')).toContain('"splash_status"')
    expect(readFileSync(path.join(repoRoot, 'apps/tauri/web/splash.html'), 'utf8')).toContain('__harnessDockSetStatus')
    expect(permission).toContain('identifier = "update-install"')
    expect(cargo).toContain('tauri-plugin-updater')
    expect(readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/lib.rs'), 'utf8')).toContain('tauri_plugin_updater::Builder')
    expect(update).toContain('HARNESSDOCK_UPDATER_PUBLIC_KEY')
    expect(update).toContain('let release = update_check().await')
    expect(update).toContain('GitHub 已发布 HarnessDock')
    expect(update).toContain('latest/download/latest.json')
    expect(update).toContain('download_and_install')
    expect(update).toContain('state.web_action.swap')
    expect(update).toContain('签名更新清单为 v')
    expect(update).toContain('on_before_exit')
    expect(update).toContain('app.restart()')
  })

  it('uses a transient startup surface for visible progress without exposing diagnostics at boot', () => {
    const tauri = readJson('apps/tauri/src-tauri/tauri.conf.json')
    const splash = tauri.app.windows.find((window: Record<string, any>) => window.label === 'splash')
    expect(splash).toMatchObject({
      url: 'splash.html',
      visible: true,
      center: true,
      decorations: false,
      closable: false,
      skipTaskbar: true,
    })
    expect(tauri.app.windows.find((window: Record<string, any>) => window.label === 'settings')).toBeUndefined()
    const settingsWindow = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/harness_window.rs'), 'utf8')
    expect(settingsWindow).toContain('"settings"')
    expect(settingsWindow).toContain('WebviewUrl::App("settings.html".into())')
    expect(settingsWindow).toContain('.on_page_load(|window, payload|')
    expect(settingsWindow).toContain('let _ = window.show()')
  })

  it('starts desktop Runtime natively and keeps a failed WebView recoverable', () => {
    const startup = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/startup.rs'), 'utf8')
    const host = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/lib.rs'), 'utf8')
    const harnessWindow = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/harness_window.rs'), 'utf8')
    const web = readFileSync(path.join(repoRoot, 'apps/tauri/web/app.js'), 'utf8')
    const index = readFileSync(path.join(repoRoot, 'apps/tauri/web/index.html'), 'utf8')

    expect(host).toContain('mod startup')
    expect(host).toContain('startup::spawn(app.handle().clone())')
    expect(host).toContain('RunEvent::ExitRequested')
    expect(host).toContain('api.prevent_exit()')
    expect(startup).toContain('runtime::start_for_boot')
    expect(startup).toContain('open_for_startup')
    expect(startup).toContain('show_startup_recovery')
    expect(startup).not.toContain('app.exit')
    expect(harnessWindow).toContain('schedule_harness_watchdog')
    expect(harnessWindow).toContain('finish_harness_load')
    expect(harnessWindow).toContain('show_startup_recovery')
    expect(harnessWindow).toContain('20 秒内没有完成加载')
    expect(web).toContain('Native startup owns the normal desktop path')
    expect(web).toContain('__harnessDockShowRecovery')
    expect(web).toContain("call('startup_recovery_status')")
    expect(web).toContain("platform.surface === 'desktop'")
    expect(index).toContain('id="shell-settings-entry" class="secondary hidden"')
    expect(index).toContain('id="shell-open-harness" class="primary hidden"')
    expect(web).not.toContain('await call(\'control_hide\')')
  })

  it('keeps direct Tauri dev/build commands connected to generated plugin assets', () => {
    const tauriPackage = readJson('apps/tauri/package.json')
    expect(tauriPackage.scripts['prepare:plugins']).toContain('@dsh/plugin-embedded-client')
    expect(tauriPackage.scripts['prepare:plugins']).toContain('@dsh/plugin-harness-shell')
    expect(tauriPackage.scripts['tauri:dev']).toContain('prepare:plugins')
    expect(tauriPackage.scripts['tauri:build']).toContain('prepare:plugins')
    expect(tauriPackage.scripts['tauri:build']).toContain('bundle:sidecar')
  })

  it('publishes the exact signed Tauri updater targets', () => {
    const tauri = readJson('apps/tauri/src-tauri/tauri.conf.json')
    const generator = readFileSync(path.join(repoRoot, 'scripts/generate-tauri-updater-manifest.mjs'), 'utf8')
    const release = readFileSync(path.join(repoRoot, '.github/workflows/release.yml'), 'utf8')
    expect(tauri.bundle.createUpdaterArtifacts).toBe(true)
    expect(generator).toContain("'windows-x86_64'")
    expect(generator).toContain("'linux-x86_64'")
    expect(generator).toContain("'darwin-x86_64'")
    expect(generator).toContain("'darwin-aarch64'")
    expect(generator).toContain('empty Tauri updater signature')
    expect(release).toContain('node scripts/generate-tauri-updater-manifest.mjs release-assets "$RELEASE_TAG"')
    expect(release).toContain('expected 20 non-empty assets')
  })

  it('keeps Windows helper processes console-free and has a final Web UI safe profile', () => {
    const platform = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/platform.rs'), 'utf8')
    const runtime = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/runtime.rs'), 'utf8')
    const gatewayHost = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/gateway_host.rs'), 'utf8')
    expect(platform).toContain('CREATE_NO_WINDOW')
    expect(runtime).toContain('platform::configure_child_command')
    expect(gatewayHost).toContain('platform::configure_child_command')
    expect(runtime).toContain('--dump-default-config')
    expect(runtime).toContain('start_safe_profile')
    expect(runtime).toContain('start_with_node_fallback')
    expect(runtime).toContain('内置 Node')
    expect(runtime).toContain('safe-dsh-home')
    expect(runtime).toContain('recovery_source: "safe-profile"')
  })

  it('declares mobile as remote-runtime-only in the Rust launcher UI contract', () => {
    const source = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/platform.rs'), 'utf8')
    expect(source).toContain('if cfg!(mobile) { "remote" } else { "local" }')
    const runtime = readFileSync(path.join(repoRoot, 'apps/tauri/src-tauri/src/runtime.rs'), 'utf8')
    expect(runtime).toContain('if cfg!(mobile)')
    expect(runtime).toContain('不允许在移动设备内启动桌面 dsh Runtime')
  })
})