import { describe, expect, it } from 'vitest'
import {
  buildCapabilityMatrix,
  parseDumpConfigMounts,
  renderCapabilityMatrixMarkdown,
} from '../src/matrix.ts'
import type { CapabilityMatrix } from '../src/types.ts'

describe('buildCapabilityMatrix', () => {
  it('merges guide capabilities with host plugin mounts from dump-config', () => {
    const matrix = buildCapabilityMatrix({
      dshVersion: '0.1.1-rc.2',
      gitTag: 'dsh-v0.1.1-rc.2',
      guide: [
        { id: 'configure-models', title: '配置模型', source: 'docs/user/guide/index.zh.md' },
        { id: 'choose-workspace', title: '选择工作区', source: 'docs/user/guide/index.zh.md' },
        { id: 'run-task', title: '运行任务', source: 'docs/user/guide/index.zh.md' },
      ],
      dumpConfig: `
- id: api-gateway
  name: '@deepseek-ai/dsh-host-apiproxy'
- id: directory-picker
  name: '@deepseek-ai/dsh-host-directory-picker-auto'
- id: workspace
  name: '@deepseek-ai/dsh-workspace'
- id: host-frontend-static
  name: '@deepseek-ai/dsh-host-frontend-static'
      `,
    })

    expect(matrix.hostMounts).toEqual({
      'api-gateway': true,
      'directory-picker': true,
      workspace: true,
      'host-frontend-static': true,
    })
    expect(matrix.operations.map((o) => o.id)).toContain('session-export')
    expect(matrix.operations.map((o) => o.id)).toContain('approval-flow')
  })
})

describe('parseDumpConfigMounts', () => {
  it('detects required web composition ids', () => {
    const mounts = parseDumpConfigMounts('- id: api-gateway\n- id: workspace\n')
    expect(mounts['api-gateway']).toBe(true)
    expect(mounts.workspace).toBe(true)
    expect(mounts['directory-picker']).toBe(false)
  })
})

describe('renderCapabilityMatrixMarkdown', () => {
  const matrix = buildCapabilityMatrix({
    dshVersion: '0.1.1-rc.2',
    gitTag: 'dsh-v0.1.1-rc.2',
    guide: [
      { id: 'configure-models', title: '配置模型', source: 'docs/user/guide/index.zh.md' },
      { id: 'run-task', title: '运行任务', source: 'docs/user/guide/index.zh.md' },
    ],
    dumpConfig: '- id: api-gateway\n- id: workspace\n',
  })

  it('includes the generated-by header, title, dshVersion and gitTag', () => {
    const markdown = renderCapabilityMatrixMarkdown(matrix)
    expect(markdown.startsWith('# Generated by @dsh/docs-sync')).toBe(true)
    expect(markdown).toContain('# HarnessDock capability matrix — dsh 0.1.1-rc.2')
    expect(markdown).toContain('- gitTag: dsh-v0.1.1-rc.2')
  })

  it('renders hostMounts true/false per id', () => {
    const markdown = renderCapabilityMatrixMarkdown(matrix)
    expect(markdown).toContain('| api-gateway | true |')
    expect(markdown).toContain('| workspace | true |')
    expect(markdown).toContain('| directory-picker | false |')
    expect(markdown).toContain('| host-frontend-static | false |')
  })

  it('lists every operation id with its title and source', () => {
    const markdown = renderCapabilityMatrixMarkdown(matrix)
    for (const op of matrix.operations) {
      expect(markdown).toContain(`- id: ${op.id}`)
      expect(markdown).toContain(op.title)
      expect(markdown).toContain(`source: ${op.source}`)
    }
  })

  it('omits the source when an operation has none (no throw)', () => {
    const noSource = {
      ...matrix,
      operations: [
        { id: 'configure-models', title: '配置模型', source: 'docs/user/guide/index.zh.md' },
        { id: 'theme-toggle', title: '浅色 / 深色主题' },
      ],
    } as unknown as CapabilityMatrix
    expect(() => renderCapabilityMatrixMarkdown(noSource)).not.toThrow()
    const markdown = renderCapabilityMatrixMarkdown(noSource)
    expect(markdown).toContain('- id: theme-toggle — 浅色 / 深色主题')
    expect(markdown).not.toContain('- id: theme-toggle — 浅色 / 深色主题（source:')
  })
})
