import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { hashDocs } from '../src/docs.ts'
import { buildOrigin } from '../src/origin.ts'
import { resolveClientVersion, syncDsh } from '../src/sync.ts'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..')

function jsonResponse(body: unknown, headers?: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status: 200,
    headers: { 'content-type': 'application/json', ...headers },
  })
}

const GUIDE_MD = '## 配置模型\n\n## 选择工作区\n\n## 运行任务\n'

/** Injected fetcher that mocks the whole GitHub tags + npm + docs pipeline. */
function mockFetchImpl(): typeof fetch {
  return async (input) => {
    const url = String(input)
    if (url.includes('/git/matching-refs/tags/dsh-v')) {
      return jsonResponse([
        {
          ref: 'refs/tags/dsh-v0.1.1-rc.1',
          object: { sha: 'aaa', type: 'commit' },
        },
        {
          ref: 'refs/tags/dsh-v0.1.1-rc.2',
          object: { sha: 'b150a551b8d465e31e418e1b2eaf5e79bbb7d28e', type: 'commit' },
        },
      ])
    }
    if (url === 'https://registry.npmjs.org/@deepseek-ai/dsh') {
      return jsonResponse({
        versions: { '0.1.1-rc.1': {}, '0.1.1-rc.2': {}, '0.0.1-rc.1': {} },
      })
    }
    if (url.endsWith('/0.1.1-rc.2')) {
      return jsonResponse({
        version: '0.1.1-rc.2',
        bin: { dsh: 'lib/bin.js' },
        dist: {
          fileCount: 20,
          integrity: 'sha512-abc',
          tarball: 'https://registry.npmjs.org/@deepseek-ai/dsh/-/dsh-0.1.1-rc.2.tgz',
        },
      })
    }
    if (url.includes('index.zh.md')) {
      return new Response(GUIDE_MD, { status: 200 })
    }
    if (url.includes('raw.githubusercontent.com')) {
      return new Response('missing', { status: 404 })
    }
    return new Response('not mocked ' + url, { status: 500 })
  }
}

function tempDir(): string {
  return mkdtempSync(path.join(os.tmpdir(), 'dsh-sync-'))
}

function tempPaths(dir: string) {
  return {
    origin: path.join(dir, 'origin.json'),
    matrix: path.join(dir, 'capability-matrix.yaml'),
    summary: path.join(dir, 'capability-summary.md'),
  }
}

describe('syncDsh', () => {
  it('picks git∩npm latest usable version and refuses a latest pin', async () => {
    await expect(syncDsh({ pin: 'latest' })).rejects.toThrow(/dist-tag/)
  })

  it('builds origin from injected fetchers', async () => {
    const fetchImpl = mockFetchImpl()

    const result = await syncDsh({ fetchImpl, dryRun: true })
    expect(result.origin.dshVersion).toBe('0.1.1-rc.2')
    expect(result.origin.gitCommit).toBe('b150a551b8d465e31e418e1b2eaf5e79bbb7d28e')
    expect(result.origin.npmIntegrity).toBe('sha512-abc')
    expect(result.written).toBe(false)
  })
})

describe('syncDsh capability summary output', () => {
  it('dry-run never writes the summary (or yaml)', async () => {
    const dir = tempDir()
    try {
      const result = await syncDsh({ fetchImpl: mockFetchImpl(), dryRun: true, paths: tempPaths(dir) })
      expect(result.written).toBe(false)
      expect(existsSync(tempPaths(dir).origin)).toBe(false)
      expect(existsSync(tempPaths(dir).matrix)).toBe(false)
      expect(existsSync(tempPaths(dir).summary)).toBe(false)
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('writes both yaml and markdown summary on a real change', async () => {
    const dir = tempDir()
    try {
      const result = await syncDsh({ fetchImpl: mockFetchImpl(), dryRun: false, paths: tempPaths(dir) })
      expect(result.changed).toBe(true)
      expect(result.written).toBe(true)

      const yaml = readFileSync(tempPaths(dir).matrix, 'utf8')
      expect(yaml).toContain('dshVersion: 0.1.1-rc.2')
      expect(yaml).toContain('- id: configure-models')

      const summary = readFileSync(tempPaths(dir).summary, 'utf8')
      expect(summary.startsWith('# Generated by @dsh/docs-sync')).toBe(true)
      expect(summary).toContain('# HarnessDock capability matrix — dsh 0.1.1-rc.2')
      expect(summary).toContain('- gitTag: dsh-v0.1.1-rc.2')
      expect(summary).toContain('| api-gateway | true |')
      expect(summary).toContain('- id: configure-models')
      expect(summary).toContain('- id: run-task')
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })

  it('does not rewrite the summary when origin is unchanged', async () => {
    const dir = tempDir()
    try {
      const expectedOrigin = buildOrigin({
        dshVersion: '0.1.1-rc.2',
        gitTag: 'dsh-v0.1.1-rc.2',
        gitCommit: 'b150a551b8d465e31e418e1b2eaf5e79bbb7d28e',
        npmIntegrity: 'sha512-abc',
        npmTarball: 'https://registry.npmjs.org/@deepseek-ai/dsh/-/dsh-0.1.1-rc.2.tgz',
        docsHash: hashDocs({ 'docs/user/guide/index.zh.md': GUIDE_MD }),
        clientVersion: '0.1.0',
        now: '2026-01-01T00:00:00.000Z',
      })
      writeFileSync(tempPaths(dir).origin, `${JSON.stringify(expectedOrigin, null, 2)}\n`, 'utf8')

      const result = await syncDsh({ fetchImpl: mockFetchImpl(), dryRun: false, paths: tempPaths(dir) })
      expect(result.changed).toBe(false)
      expect(result.written).toBe(false)
      expect(existsSync(tempPaths(dir).matrix)).toBe(false)
      expect(existsSync(tempPaths(dir).summary)).toBe(false)
    } finally {
      rmSync(dir, { recursive: true, force: true })
    }
  })
})

describe('resolveClientVersion', () => {
  it('matches the repo root package.json version', () => {
    const rootPackageJson = JSON.parse(
      readFileSync(path.join(repoRoot, 'package.json'), 'utf8'),
    ) as { version: string }
    expect(resolveClientVersion()).toBe(rootPackageJson.version)
  })
})
