import {
  RUNTIME_READY_LOOPBACK_HOST,
} from './runtime-ready-contract.generated.ts'
import type { ReadyInfo } from './types.ts'

export interface ReadyExpectation {
  dshVersion: string
  pid: number
  generation: number
  nonce: string
  imageIdentity: string
}

/**
 * Parse only an authoritative, generation-bound ready file.
 *
 * Stdout URLs are diagnostics, never a readiness boundary. A ready file is
 * accepted only when it belongs to the exact process and binding generated by
 * the current host start operation and the URL resolves to that same loopback
 * origin.
 */
export function parseReadyFile(raw: string, expected: ReadyExpectation): ReadyInfo | null {
  try {
    const parsed = JSON.parse(raw) as Partial<ReadyInfo>
    if (
      typeof parsed.url !== 'string' ||
      parsed.host !== RUNTIME_READY_LOOPBACK_HOST ||
      typeof parsed.port !== 'number' ||
      !Number.isInteger(parsed.port) ||
      parsed.port <= 0 ||
      parsed.port > 65535 ||
      typeof parsed.pid !== 'number' ||
      !Number.isInteger(parsed.pid) ||
      parsed.pid <= 0 ||
      typeof parsed.dshVersion !== 'string' ||
      typeof parsed.generation !== 'number' ||
      !Number.isSafeInteger(parsed.generation) ||
      parsed.generation <= 0 ||
      typeof parsed.nonce !== 'string' ||
      parsed.nonce.length === 0 ||
      typeof parsed.imageIdentity !== 'string' ||
      parsed.imageIdentity.length === 0
    ) {
      return null
    }
    if (
      parsed.pid !== expected.pid ||
      parsed.dshVersion !== expected.dshVersion ||
      parsed.generation !== expected.generation ||
      parsed.nonce !== expected.nonce ||
      parsed.imageIdentity !== expected.imageIdentity
    ) {
      return null
    }

    const url = new URL(parsed.url)
    if (
      url.protocol !== 'http:' ||
      url.hostname !== RUNTIME_READY_LOOPBACK_HOST ||
      Number(url.port) !== parsed.port ||
      url.username !== '' ||
      url.password !== ''
    ) {
      return null
    }
    return parsed as ReadyInfo
  } catch {
    return null
  }
}
