// @generated by scripts/generate-shell-contract.mjs. DO NOT EDIT.
export const SHELL_API_VERSION = 2 as const
export const SHELL_PLUGIN_ID = "harness-shell" as const
export const SHELL_VERSION = "0.1.2" as const
export const SHELL_COMMANDS = [
  "window.minimize",
  "window.toggleMaximize",
  "window.state",
  "window.close",
  "web.reload",
  "web.restart",
  "runtime.safe-mode",
  "gateway.manage",
  "diagnostics.open"
] as const
