// @generated by scripts/generate-host-protocol.mjs. DO NOT EDIT.

pub const HOST_PROTOCOL_VERSION: u16 = 2;

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum SubjectKind {
    #[serde(rename = "desktop-shell")]
    DesktopShell,
    #[serde(rename = "harness-web")]
    HarnessWeb,
    #[serde(rename = "native-menu")]
    NativeMenu,
    #[serde(rename = "tray")]
    Tray,
    #[serde(rename = "diagnostics")]
    Diagnostics,
    #[serde(rename = "mobile")]
    Mobile,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
pub enum Capability {
    #[serde(rename = "window-control")]
    WindowControl,
    #[serde(rename = "web-reload")]
    WebReload,
    #[serde(rename = "runtime-restart")]
    RuntimeRestart,
    #[serde(rename = "runtime-safe-mode")]
    RuntimeSafeMode,
    #[serde(rename = "runtime-clear-quarantine")]
    RuntimeClearQuarantine,
    #[serde(rename = "gateway-manage")]
    GatewayManage,
    #[serde(rename = "diagnostics-read")]
    DiagnosticsRead,
    #[serde(rename = "update-check")]
    UpdateCheck,
    #[serde(rename = "update-install")]
    UpdateInstall,
    #[serde(rename = "app-quit")]
    AppQuit,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(tag = "type")]
pub enum HostCommand {
    #[serde(rename = "refresh-harness")]
    RefreshHarness,
    #[serde(rename = "restart-runtime")]
    RestartRuntime,
    #[serde(rename = "start-safe-mode")]
    StartSafeMode,
    #[serde(rename = "clear-quarantine")]
    ClearQuarantine,
    #[serde(rename = "show-gateway")]
    ShowGateway,
    #[serde(rename = "show-diagnostics")]
    ShowDiagnostics,
    #[serde(rename = "install-update")]
    InstallUpdate,
    #[serde(rename = "quit")]
    Quit,
}

impl HostCommand {
    pub const fn capability(&self) -> Capability {
        match self {
            Self::RefreshHarness => Capability::WebReload,
            Self::RestartRuntime => Capability::RuntimeRestart,
            Self::StartSafeMode => Capability::RuntimeSafeMode,
            Self::ClearQuarantine => Capability::RuntimeClearQuarantine,
            Self::ShowGateway => Capability::GatewayManage,
            Self::ShowDiagnostics => Capability::DiagnosticsRead,
            Self::InstallUpdate => Capability::UpdateInstall,
            Self::Quit => Capability::AppQuit,
        }
    }
}
