// @generated by scripts/generate-shell-contract.mjs. DO NOT EDIT.

pub const SHELL_API_VERSION: u16 = 2;
pub const SHELL_PLUGIN_ID: &str = "harness-shell";
pub const SHELL_VERSION: &str = "0.1.2";
pub const SHELL_DIRECT_WINDOW_MAP_JSON: &str = r#"{"window.minimize":"harness_minimize","window.toggleMaximize":"harness_toggle_maximize","window.state":"harness_window_state","window.close":"harness_shell_close"}"#;
pub const SHELL_HOST_COMMAND_MAP_JSON: &str = r#"{"web.reload":"refresh-harness","web.restart":"restart-runtime","runtime.safe-mode":"start-safe-mode","gateway.manage":"show-gateway","diagnostics.open":"show-diagnostics"}"#;
