// @generated by scripts/generate-runtime-ready-contract.mjs. DO NOT EDIT.
export const RUNTIME_READY_LOOPBACK_HOST = "127.0.0.1" as const
export const RUNTIME_READY_ENV = Object.freeze({
  "readyFile": "DSH_EMBEDDED_READY_FILE",
  "dshVersion": "DSH_EMBEDDED_VERSION",
  "generation": "HARNESSDOCK_RUNTIME_GENERATION",
  "nonce": "HARNESSDOCK_RUNTIME_NONCE",
  "imageIdentity": "HARNESSDOCK_RUNTIME_IMAGE_IDENTITY"
})
export const RUNTIME_READY_FIELDS = [
  "url",
  "host",
  "port",
  "pid",
  "dshVersion",
  "generation",
  "nonce",
  "imageIdentity"
] as const
